baseURL = "http://127.0.0.1:8080/"
languageCode = "pt-br"
title = "Home"
theme = "PaperMod"

[params]
defaultTheme = "dark"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
displayFullLangName = true

[params.profileMode]
enabled = true
title = "DEVOPS ENGINEER | CLOUD ANALYST"
subtitle = "Welcome to my Blog"
imageUrl = "/images/brendo.png"
imageWidth = 240
imageHeight = 240
imageTitle = "Meu Avatar"

[[params.profileMode.buttons]]
name = "Posts"
url = "/posts"

[[params.profileMode.buttons]]
name = "Tags"
url = "/tags"

[[params.profileMode.buttons]]
name = "Portfólio"
url = "/portfolio"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/brendo-trindade/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/BrendoTrindade"

[[params.socialIcons]]
name = "telegram"
url = "https://t.me/brendo_trindade"

[[params.socialIcons]]
name = "email"
url = "mailto:brendofut44@gmail.com"

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 10

[[menu.main]]
name = "Portfólio"
url = "/portfolio/"
weight = 20

[[menu.main]]
name = "Sobre Mim"
url = "/sobre-mim/"
weight = 30

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 40

[[menu.main]]
name = "Resumo"
url = "https://rxresu.me/brendo.trindade/resumo"
weight = 50

[[menu.main]]
name = "Linktree"
url = "https://linktr.ee/brendo_trindade"
weight = 60

[markup.goldmark.renderer]
unsafe = true
