[build]
publish = "public"
command = "hugo"

[build.environment]
HUGO_VERSION = "0.125.7"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
