[build]
command = """
hugo --gc --minify
cp -r static/* public/
"""
publish = "public"

[build.environment]
HUGO_VERSION = "0.123.8"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.production.environment]
HUGO_ENV = "production"

[[plugins]]
package = "netlify-plugin-hugo-cache-resources"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
